import { jsPDF } from 'jspdf';
import type { AnalysisResult } from '../data/placeholder';

/**
 * Generates a clean, professional PDF product insights report entirely
 * in the browser. Layout:
 *   - Title block + meta (date, source file, reviews)
 *   - Executive Summary
 *   - Top Customer Complaints
 *   - Top Praised Features
 *   - Feature Requests
 *   - Product Recommendations
 *   - Footer "Generated by InsightLens AI" on every page
 *   - Page numbers when multiple pages are needed
 */
export function exportInsightsPdf(result: AnalysisResult): void {
  const doc = new jsPDF({ unit: 'pt', format: 'a4' });
  const pageW = doc.internal.pageSize.getWidth();
  const pageH = doc.internal.pageSize.getHeight();

  const margin = 48;
  const contentW = pageW - margin * 2;
  let y = margin;

  const ink = { 900: '#15181d', 700: '#363b48', 500: '#646c7d', 300: '#b9bfca' };
  const brand = '#3563f5';
  const rule = '#e0e3ea';

  const ensureSpace = (needed: number) => {
    if (y + needed > pageH - margin - 28) {
      addFooter();
      doc.addPage();
      y = margin;
    }
  };

  const addFooter = () => {
    const footerY = pageH - 32;
    doc.setDrawColor(rule);
    doc.setLineWidth(0.5);
    doc.line(margin, footerY - 10, pageW - margin, footerY - 10);

    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(ink[500]);
    doc.text('Generated by InsightLens AI', margin, footerY);
  };

  const heading = (text: string) => {
    ensureSpace(46);
    y += 10;
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(13);
    doc.setTextColor(ink[900]);
    doc.text(text, margin, y);
    y += 7;
    doc.setDrawColor(rule);
    doc.setLineWidth(0.8);
    doc.line(margin, y, pageW - margin, y);
    y += 14;
  };

  const body = (text: string, opts?: { italic?: boolean; size?: number; color?: string; gap?: number }) => {
    const size = opts?.size ?? 10;
    doc.setFont('helvetica', opts?.italic ? 'italic' : 'normal');
    doc.setFontSize(size);
    doc.setTextColor(opts?.color ?? ink[700]);
    const lines = doc.splitTextToSize(text, contentW) as string[];
    const lineH = size * 1.5;
    for (const line of lines) {
      ensureSpace(lineH);
      doc.text(line, margin, y);
      y += lineH;
    }
    y += opts?.gap ?? 6;
  };

  const metaRow = (label: string, value: string) => {
    ensureSpace(18);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(ink[500]);
    doc.text(label.toUpperCase(), margin, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(ink[900]);
    doc.text(value, margin + 120, y);
    y += 18;
  };

  /* ---------- Title block ---------- */
  doc.setFont('helvetica', 'bold');
  doc.setFontSize(20);
  doc.setTextColor(ink[900]);
  doc.text('InsightLens AI', margin, y);
  y += 8;

  doc.setDrawColor(brand);
  doc.setLineWidth(2);
  doc.line(margin, y, margin + 36, y);
  y += 18;

  doc.setFont('helvetica', 'normal');
  doc.setFontSize(13);
  doc.setTextColor(ink[500]);
  doc.text('Product Insights Report', margin, y);
  y += 16;

  doc.setDrawColor(rule);
  doc.setLineWidth(0.8);
  doc.line(margin, y, pageW - margin, y);
  y += 14;

  /* ---------- Meta ---------- */
  const now = new Date();
  const dateStr = now.toLocaleDateString(undefined, {
    year: 'numeric',
    month: 'long',
    day: 'numeric',
  });
  const timeStr = now.toLocaleTimeString(undefined, {
    hour: '2-digit',
    minute: '2-digit',
  });

  metaRow('Date', `${dateStr} · ${timeStr}`);
  metaRow('Source File', result.source.name);
  metaRow('Reviews Analyzed', result.source.reviews.toLocaleString());
  y += 6;

  /* ---------- Executive Summary ---------- */
  heading('Executive Summary');
  body(result.executiveSummary, { gap: 10 });
  if (result.summaryPoints.length) {
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(9);
    doc.setTextColor(ink[500]);
    ensureSpace(14);
    doc.text('KEY POINTS', margin, y);
    y += 14;
    for (const p of result.summaryPoints) {
      ensureSpace(16);
      doc.setTextColor(brand);
      doc.setFont('helvetica', 'bold');
      doc.setFontSize(10);
      doc.text('•', margin, y);
      body(p.text, { size: 10, gap: 2 });
    }
  }

  /* ---------- Top Customer Complaints ---------- */
  heading('Top Customer Complaints');
  if (result.complaints.length === 0) {
    body('No complaints detected.', { color: ink[300] });
  }
  result.complaints.forEach((c, i) => {
    ensureSpace(34);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(ink[900]);
    doc.text(`${i + 1}.`, margin, y);
    doc.text(c.title, margin + 18, y);
    y += 14;
    body(
      `${c.mentions.toLocaleString()} mentions · ${c.share}% of negative reviews · ${c.severity} severity`,
      { size: 9, color: ink[500], gap: 4 },
    );
    body(c.excerpt, { italic: true, size: 9, color: ink[500], gap: 8 });
  });

  /* ---------- Top Praised Features ---------- */
  heading('Top Praised Features');
  if (result.praised.length === 0) {
    body('No praised features detected.', { color: ink[300] });
  }
  result.praised.forEach((f, i) => {
    ensureSpace(20);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(ink[900]);
    doc.text(`${i + 1}.`, margin, y);
    doc.text(f.name, margin + 18, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(ink[500]);
    doc.text(
      `Score ${f.score.toFixed(1)}/5 · ${f.mentions.toLocaleString()} mentions · ${f.category}`,
      pageW - margin,
      y,
      { align: 'right' },
    );
    y += 18;
  });

  /* ---------- Feature Requests ---------- */
  heading('Feature Requests');
  if (result.requests.length === 0) {
    body('No feature requests detected.', { color: ink[300] });
  }
  result.requests.forEach((r, i) => {
    ensureSpace(34);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(ink[900]);
    doc.text(`${i + 1}.`, margin, y);
    doc.text(r.title, margin + 18, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(ink[500]);
    doc.text(
      `${r.votes} votes · ${r.priority} priority`,
      pageW - margin,
      y,
      { align: 'right' },
    );
    y += 14;
    body(r.rationale, { size: 9, color: ink[500], gap: 8 });
  });

  /* ---------- Product Recommendations ---------- */
  heading('Product Recommendations');
  if (result.recommendations.length === 0) {
    body('No recommendations available.', { color: ink[300] });
  }
  result.recommendations.forEach((r, i) => {
    ensureSpace(34);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(11);
    doc.setTextColor(ink[900]);
    doc.text(`${i + 1}.`, margin, y);
    doc.text(r.title, margin + 18, y);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(9);
    doc.setTextColor(ink[500]);
    doc.text(
      `${r.impact} impact · ${r.effort} effort · ${r.timeframe}`,
      pageW - margin,
      y,
      { align: 'right' },
    );
    y += 14;
    body(r.description, { size: 9, color: ink[500], gap: 8 });
  });

  /* ---------- Final footer on last page ---------- */
  addFooter();

  /* ---------- Page numbers across all pages ---------- */
  const total = doc.getNumberOfPages();
  for (let p = 1; p <= total; p++) {
    doc.setPage(p);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(8);
    doc.setTextColor(ink[500]);
    doc.text(`Page ${p} of ${total}`, pageW - margin, pageH - 32, {
      align: 'right',
    });
  }

  const safeName = result.source.name.replace(/[^a-z0-9]+/gi, '_');
  doc.save(`InsightLens_AI_Product_Insights_${safeName}.pdf`);
}
